---
title: "Package internal implementation notes"
author: "Matthieu"
date: "October 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes
...


## To do

### BUGS



### Short term

* `?seglm` returns general help?
* correct mismatch grid/dynprog. DONE
* push to github DONE
* rename functions, needs consistency DONE
* dynprog for more than 2 nthresh!! DONE
* dynprog only return SSR if necessary! DONE
* clean utilities.R some not used anymore
* add third method:  grid with recresid, much faster!
* understand effect of ordering over threshold then use structural break techniques



### Further functionalities:

* grid should work for matrix Y! Easy for algo search, need to generalize recresid?!

### Further functions:

* Add function `get_th_int()`: returns empirical intervals, for observed values?
* `seglm_lm()` "workhorse" function. IN PROGRESS
* add function `regime()` IN PROGRESS
* `predict()`: option to feed raw data, transform then
* broom/tidy implementation: 
    - `augment()`: add `regime()`?
    - `tidy()` add threshold
* Hansen `confint()`
* Handle variables with no switch!?

## Long term functionalitites to add:

* shrinkage method for threshold
* bootstrap? look at new paradigms...
* Linton Seo (look at `nls()` and partially linear LS literature ) 
* Greb shrinkage stuff. 
* Generalized grid search for `glm()`, or any. Look at Seo JASA paper!
* datasets from Hansen 2000!? https://www.ssc.wisc.edu/~bhansen/progs/ecnmt_00.html
